### ISSUE TITLE
User Story 1 - Event List ✅

### ISSUE THREAD

**Issue by toshydev** [toshydev/capstone-inspot#1]
## Value proposition

**As a user
I want a to see a list of events
So that I can inform myself about my options on each day**

## Description

![US-1 wireframe](https://user-images.githubusercontent.com/91165689/228919063-ebcf3311-a56f-448a-a12e-e86c0998c815.png)

- A list of all events that are present in the data

## Acceptance criteria

- [x] **All** events from the data should be displayed on the EventListPage 🖼️
- [x] Each event should display an event **name** and **date** 🖼️

## Tasks

- [x] Create a dummy data file `events.json`
- [x] Create an `EventListPage` component and pass it an `events` prop
- [x] Create an `EventPreview` component and pass it an `event` prop
- [x] Display the `event.title` and `event.date` in the `EventPreview` component
- [x] Acceptance criteria with 🖼️ requires component testing
