### ISSUE TITLE
User Story 2 - Location Page ✅

### ISSUE THREAD

**Issue by toshydev** [toshydev/capstone-inspot#2]
## Value proposition

**As a user
I want to be able to see a list of cities
So that I can filter events by location**

## Description

![US-2 wireframe](https://user-images.githubusercontent.com/91165689/228921285-7c61771f-d144-49f7-9bf8-9a3c5970ded6.png)

- List of cities to set a location from

## Acceptance criteria

- [x] Cities which are present in the data should be displayed 🖼️
- [x] Each city should display a city name 🖼️

## Tasks

- [x] Create an array of cities from all event locations in `events.json`
- [x] Create a `LocationPage` component and pass it a `cities` array as a prop
- [x] Map through `cities` and render each city as a list item with a city `name`
- [x] Acceptance criteria with 🖼️ requires component testing

**Comment by rabe200** [comment]
lgtm besides of the missing "i" in "So that can filter events by city" :)
