### ISSUE TITLE
User Story 9 - Fetch API 🎯

### ISSUE THREAD

**Issue by toshydev** [toshydev/capstone-inspot#22]
## Value proposition

**As a user
I want to see events from the Ticketmaster API
So that I can pick an event from a list of real events**

## Description

- Dummy data is replaced by data from the Ticketmaster API

## Acceptance criteria

- [x] Events from the Ticketmaster API are shown instead of events from `data.js`
- [x] Error handling is implemented

## Tasks

- [x] Setup fetching logic in the `/api` folder
- [x] Include the API key in `.env`
- [x] Acceptance criteria with 🧪 requires component testing

Complexity: XL

**Comment by manukao** [comment]
Short and clear description of the next feature, lgtm 👍
