### ISSUE TITLE
User Story 10 - Venues List 🎯

### ISSUE THREAD

**Issue by toshydev** [toshydev/capstone-inspot#23]
## Value proposition

**As a user
I want a to see a list of venues
So that I see which venues are available**

## Description

![US-10-VenuesList](https://user-images.githubusercontent.com/91165689/231135186-32721950-0a0f-432f-91a9-c10c91cef6be.png)
- A list of venues is shown

## Acceptance criteria

- [x] All venues passed to the `VenuesList` are rendered 🧪
- [x] A heading is rendered for each venue in the list 🧪

## Tasks

- [x] Create a `VenuesList` component and pass it a prop `venues`
- [x] Acceptance criteria with 🧪 requires component testing

Complexity: M

**Comment by malgosiam** [comment]
LGTM! only a minor typo in the acceptance criteria: All venues passed to the VenuesList are rendered
