### ISSUE TITLE
User Story 11 - Spotlight Page 🎯

### ISSUE THREAD

**Issue by toshydev** [toshydev/capstone-inspot#24]
## Value proposition

**As a user
I want to land on a spotlight page
So that see suggested events from venues**

## Description

![US-11-SpotlightPage](https://user-images.githubusercontent.com/91165689/231139854-f4da0c04-bec0-4a51-be3a-f4c9cb1dd5e3.png)
- A list of suggested venues with corresponding events is displayed

## Acceptance criteria

- [ ] A list of events is rendered with a event title and venue name 🧪

## Tasks

- [ ] Fetch a suggested events list with corresponding events
- [ ] Acceptance criteria with 🧪 requires component testing

Complexity: L

**Comment by Satttoshi** [comment]
Alter Schwede

So eine gute Idee, allein von der Darstellung. Mega intuitiv und nice. Richtig virtuos 

lvgtm :rocket:
