### ISSUE TITLE
User Story 12 - Navigation Bar 🎯

### ISSUE THREAD

**Issue by toshydev** [toshydev/capstone-inspot#25]
## Value proposition

**As a user
I want to see a navigation bar
So that I can navigate between the *Venues* and *Explore* pages**

## Description

![US-12-NavigationBar](https://user-images.githubusercontent.com/91165689/231167474-128c6072-dc5a-45fc-8e20-fba34175fb0c.png)
- A navigation bar with Explore and Venues links

## Acceptance criteria

- [ ] The `NavigationBar` component renders two links 🧪

## Tasks

- [ ] Create the `NavigationBar` component and link to the respective pages
- [ ] Acceptance criteria with 🧪 requires component testing

Complexity: S

**Comment by DominicWebDev** [comment]
I clicked almost every site, works as described 
Good JOB !
