### ISSUE TITLE
User Story 13 - Venue Details 🎯

### ISSUE THREAD

**Issue by toshydev** [toshydev/capstone-inspot#26]
## Value proposition

**As a user
I want to see a venue details page
So that I can see important information about the chosen venue**

## Description
![Image](https://user-images.githubusercontent.com/91165689/231178572-2a692da7-cae3-4c18-b8e1-d57e8ad7e839.png)
- A venue details page with information like address and upcoming events

## Acceptance criteria

- [x] The `VenueDetailsPage` renders the name, address and a picture of the venue if available
- [x] A list of previews of upcoming events of the chosen venue are rendered

## Tasks

- [x] Create a `VenueDetailsPage` component and pass it a `venue` prop
- [x] Fetch events for the passed `venue` prop
- [x] Acceptance criteria with 🧪 requires component testing

Complexity: M

**Comment by rabe200** [comment]
lgtm!

**Comment by manukao** [comment]
lgtm 👍 

FYI: I observed two things when testing your App. 

1.) I think you don't want the white/empty "starts in ..." bar in the upper card which shows a picture and the address of the venue, do you?
2.) Occassionally the details pages would show no data or no events, see screenshots. However, when waiting long enough the data would appear. Could take like 1-10seconds. 

![Bildschirm­foto 2023-04-16 um 16 04 05](https://user-images.githubusercontent.com/97320894/232316684-56879412-1468-46ca-a97a-aa8022c2d66e.png)

![Bildschirm­foto 2023-04-16 um 16 04 22](https://user-images.githubusercontent.com/97320894/232316705-ef0271bf-0943-4100-bf30-e03f3c8f62e1.png)

**Comment by toshydev** [comment]
Thanks for the info! I will take care of the EventDetail page in the next sprint 💪
