### ISSUE TITLE
User Story 14 - Save Button 🎯

### ISSUE THREAD

**Issue by toshydev** [toshydev/capstone-inspot#27]
## Value proposition

**As a user
I want to be able to mark events as saved
So that I can save events I'm interested in**

## Description
![Image](https://user-images.githubusercontent.com/91165689/231185277-36da206f-60f5-496a-a584-fa0379d9054e.png)
- A Save Button is available for Events

## Acceptance criteria

- [x] The `EventPreview` component renders a save button 🧪
- [x] The `EventDetail` component renders a save button 🧪
- [x] Clicking the save button toggles the save property for the event in the local state store

## Tasks

- [x] Create a `SaveEventButton` that accepts an event `id`
- [x] Acceptance criteria with 🧪 requires component testing

Complexity: L

**Comment by Stephan-mit-Ph** [comment]
LGTM 🚀💥
