### ISSUE TITLE
User Story 15 - Saved Events Page 🎯

### ISSUE THREAD

**Issue by toshydev** [toshydev/capstone-inspot#28]
## Value proposition

**As a user
I want to be able to see saved events
So that I can find saved events easily**

## Description

![Image](https://user-images.githubusercontent.com/91165689/231175400-5e6eb2c3-a0da-4511-886e-28ae3b6856cf.png)
- A list of saved events

## Acceptance criteria

- [x] The `SavedEventsList` component renders a headline, date, SaveButton for all events from the passed `events` prop 🧪
- [x] Unsaving events from the SavedEventsList removes the unsaved event from the list
- [x] A `Saved` Link is displayed in the header on all pages 🧪

## Tasks

- [x] Create a `SavedEventsList` component and pass it an `events` prop
- [x] Create and add a `SavedEvents` Link to the global header
- [ ] Acceptance criteria with 🧪 requires component testing

Complexity: M

**Comment by alexWaligorski** [comment]
Looks good to me and is an awesome feature! I would be curious though, why you add the "saved Link" in the header and not in the navbar?
