### ISSUE TITLE
User Story 16 - Favorite Button 🎯

### ISSUE THREAD

**Issue by toshydev** [toshydev/capstone-inspot#29]
## Value proposition

**As a user
I want to be able to mark venues as favorite
So that I can save venues I'm interested in**

## Description
![Image](https://user-images.githubusercontent.com/91165689/231193276-5583aa80-f048-434e-b902-94b3ab3228e7.png)
- A Favorite Button is available for Venues

## Acceptance criteria

- [ ] The `VenuePreview` component renders a favorite button 🧪
- [ ] The `VenueDetail` component renders a favorite button 🧪
- [ ] Clicking the favorite button toggles the favorite property for the venue in the local state store

## Tasks

- [ ] Create a `FavoriteButton` that accepts a venue `id`
- [ ] Acceptance criteria with 🧪 requires component testing

Complexity: L

**Comment by augustinanders** [comment]
Looks good to me!
