### ISSUE TITLE
User Story 3 - Event Details ✅

### ISSUE THREAD

**Issue by toshydev** [toshydev/capstone-inspot#3]
## Value proposition

**As a user
I want a see details about the event
So that I can read a description of the event**

## Description

![US-3 wireframe](https://user-images.githubusercontent.com/91165689/228924769-1b865fe9-6e7b-48bc-8772-3cca67cfbf19.png)
- Precise, no unnecessary information

## Acceptance criteria

- [x] The event `title`, `startDate`, `endDate`, `startTime`, `endTime`, `address` should be displayed 🖼️
- [x] A `description` and `link` of the event should be displayed if available 🖼️

## Tasks

- [x] Create an `EventDetailPage` component and pass it an `event` prop
- [x] Render all event information available in the page
- [x] Acceptance criteria with 🖼️ requires component testing
