### ISSUE TITLE
User Story 17 - Favorite Venues List 🎯

### ISSUE THREAD

**Issue by toshydev** [toshydev/capstone-inspot#30]
## Value proposition

**As a user
I want to be able to see favorite venues
So that I can edit my favorite venues

## Description
![Image](https://user-images.githubusercontent.com/91165689/231197666-9e88ff3e-10f1-4d75-b6fb-ece3f64e34be.png)
- A list of saved events

## Acceptance criteria

- [x] The `SavedVenuesList` component renders a name and FavoriteButton for all venues from the passed `venues` prop 🧪
- [x] Unsaving venues from the SavedVenuesList removes the unsaved venue from the list

## Tasks

- [x] Create a `SavedEventsList` component and pass it an `events` prop
- [ ] Acceptance criteria with 🧪 requires component testing

Complexity: M

**Comment by rabe200** [comment]
lgtm, just some suggestion for the value proposition: "I want to be able to see favorite venues
So that I can edit my favorites" -> feels less redundant
