### ISSUE TITLE
User Story 4 - Event Filter ✅

### ISSUE THREAD

**Issue by toshydev** [toshydev/capstone-inspot#4]
## Value proposition

As a user
I want to be able to filter the event list
So that I can focus on events I find interesting

## Description

![US-4 wireframe](https://user-images.githubusercontent.com/91165689/228937722-93f2173a-57aa-4118-a9e2-096e66873b20.png)

- A filter bar lets the user filter for genre or custom tags or remove the filter

## Acceptance criteria

- [x] Setting a genre filter should only display events of the selected genre 🖼️
- [x] Setting a custom tag should only display events with the selected tag in its description or info 🖼️
- [x] Setting a genre filter and a custom tag should only display events of the selected genre that include the tag in the description or info 🖼️
- [x] Unsetting the filter should display all events 🖼️

## Tasks

- [x] Create an `EventFilter` component and pass it the props `genre` and `tags`
- [x] Create states for `genre` and `tags`
- [x] Create a select element for setting the `genre` state 
- [x] Create an input element for setting the `tags` state
- [x] Create a button for resetting the `genre` and `tags` states
- [x] Create a `genres` variable for the genre select options
- [x] Create an onSetFilter function that sets the `filteredEvents` array
- [x] Replace the `events` prop in the `EventList` component with `filteredEvents`
- [x] Acceptance criteria with 🖼️ requires component testing

Complexity: L

**Comment by ella-blaupause** [comment]
LGTM👍
