### ISSUE TITLE
User Story 18 - Review Venue

### ISSUE THREAD

**Issue by toshydev** [toshydev/capstone-inspot#40]
## Value proposition

**As a user
I want to be able to write a review for a venue
So that I can share my experience with other users**

## Description
![Image](https://user-images.githubusercontent.com/91165689/232722334-b9a47cb4-92d5-4448-b927-9ffaab9d131b.png)
- A review section with a form and review list is visible.

## Acceptance criteria

- [ ] The `VenueDetail` component renders a form `ReviewSection` 🧪
- [ ] The `VenueDetail` component renders a rating (1-5) based on ratings in reviews 🧪
- [ ] The `VenueDetail` component renders the number of reviews 🧪
- [ ] The `ReviewSection` component renders a form `ReviewForm` and a list of reviews `ReviewList` 🧪
- [ ] Submitting a review with the `ReviewForm` adds a review to the `ReviewList` 🧪

## Tasks

- [ ] Create and connect MongoDB collections for venues and reviews respectively
- [ ] Acceptance criteria with 🖼️ requires component testing

Complexity: XL

**Comment by AnjaSiewert** [comment]
LGTM 💪🏼
I think you used the wrong emoticon in tasks for the component testing ;)
