### ISSUE TITLE
User Story 19 - Review Event

### ISSUE THREAD

**Issue by toshydev** [toshydev/capstone-inspot#41]
## Value proposition

**As a user
I want to be able to write a review for an event
So that I can share my experience with other users**

## Description
![Image](https://user-images.githubusercontent.com/91165689/232727430-fdf2369c-34b6-41a0-bffa-7509d97b0e82.png)
- A review section with a form and review list is visible.

## Acceptance criteria

- [ ] The `EventDetail` component renders a `ReviewSection` 🧪
- [ ] The `EventDetail` component renders a rating (1-5) based on ratings in reviews 🧪
- [ ] The `EventDetail` component renders the number of reviews 🧪
- [ ] The `ReviewSection` component renders a form `ReviewForm` and a list of reviews `ReviewList` 🧪
- [ ] Submitting a review with the `ReviewForm` adds a review to the `ReviewList` 🧪

## Tasks

- [ ] Create and connect MongoDB collections for events respectively
- [ ] Acceptance criteria with 🧪 requires component testing

Complexity: XL

**Comment by AnjaSiewert** [comment]
@anja_nas || Great!!  6/5 ⭐️

**Comment by AnjaSiewert** [comment]
@anja_nas || Great!!  6/5 ⭐️

    I can definitely recommend working with Anton, he is 🚀

                                                     today
