### ISSUE TITLE
User Story 20 - Profile Page

### ISSUE THREAD

**Issue by toshydev** [toshydev/capstone-inspot#42]
## Value proposition

**As a user
I want to see a profile page
So that I can access my upcoming events, venues and reviews faster**

## Description
![Image](https://user-images.githubusercontent.com/91165689/232729050-205c74e4-4ee4-4dab-a850-ab931762fc2a.png)
- A profile page with user infos and upcoming events

## Acceptance criteria

- [ ] The `ProfilePage` renders a filtered `EventsList`, username, saved items and reviews count 🧪
- [ ] The `ProfilePage` renders a username and savedEvents count, savedVenues count, userReviews count 🧪

## Tasks

- [ ] Create and connect MongoDB collections for users
- [ ] Acceptance criteria with 🧪 requires component testing

Complexity: XL
