### ISSUE TITLE
User Story 21 - User Login

### ISSUE THREAD

**Issue by toshydev** [toshydev/capstone-inspot#43]
## Value proposition

**As a user
I want to be able to log in with popular services
So that I can have my data stored securely in a database**

## Acceptance criteria

- [ ] Log in with *GitHub*, *Google* etc is possible
- [ ] Privacy policy and terms and conditions are available in the footer of the `ProfilePage`

## Tasks

- [ ] Implement next/auth

Complexity: XL

**Comment by rabe200** [comment]
lgtm!
