### ISSUE TITLE
User Story 5 - Location Navigation ✅

### ISSUE THREAD

**Issue by toshydev** [toshydev/capstone-inspot#5]
## Value proposition

**As a user
I want to be able to navigate between the pages
So that I can adjust the location and move back to the previous page**

## Description

![US-5 wireframe](https://user-images.githubusercontent.com/91165689/228941308-c7006946-72db-44b5-9567-49c5096f8f34.png)
- A navigation header with a location button and a back button

## Acceptance criteria

- [x] The `EventListPage` component renders link to the `LocationPage` 🖼️
- [x] The `LocationPage` and `EventDetailsPage` components render a link back to the `EventListPage` 🖼️

## Tasks

- [x] Add a Link to the EventListPage that has the href attribute `/pages/location`
- [x] Add a Link to the LocationPage and EventDetailPage that has the href attribute `/`
- [x] Acceptance criteria with 🖼️ requires component testing

Complexity: S

**Comment by rabe200** [comment]
lgtm! :)
