### ISSUE TITLE
User Story 6 - Current Location ✅

### ISSUE THREAD

**Issue by toshydev** [toshydev/capstone-inspot#6]
## Value proposition

**As a user
I want a to be able to use my current device location
So that I can get the exact distance to events**

## Description

- An additional choice called `Current Location` is available on the `LocationPage`

## Acceptance criteria

- [x] The `LocationPage` renders an additional item with the value of `userLocation` 🖼️
- [x] Clicking the `Current Location` entry should ask the user for permission to access the device location
- [x] The `EventListPage` should render events with the same city as the user

## Tasks

- [x] Add an additional local storage state `userLocation` and let it default to `false`
- [x] If `userLocation` true, use `userLocation` as default location, else set to `false`
- [x] Acceptance criteria with 🖼️ requires component testing

Complexity: L
