### ISSUE TITLE
User Story 7 - Event Distance 🎯

### ISSUE THREAD

**Issue by toshydev** [toshydev/capstone-inspot#7]
## Value proposition

**As a user
I want to see the distance to events in the `EventListPage` and `EventDetailPage` 
So that I can decide on an event based on distance**

## Description

- The distance to the event from the user's location is shown

## Acceptance criteria

- [x] Setting the `userLocation` to `true` should display the distance to events in the `EventListPage` 
- [x] Setting the `userLocation` to `true` should display the distance to events in the `EventDetailPage`
- [x] Moving towards an event should decrease the displayed distance
- [x] Moving away from an event should increase the displayed distance

## Tasks

- [x] Implement an API for resolving Geolocations and calculate the distance using the *Haversine* formula.
- [x] Acceptance criteria with 🖼️ requires component testing

Complexity: M

**Comment by Satttoshi** [comment]
Its helpful for future planning to add a complexity value or weigth,
so you know how much you are capable off in a week

else LGTM
