### ISSUE TITLE
User Story 8 - Time Until Event 🎯

### ISSUE THREAD

**Issue by toshydev** [toshydev/capstone-inspot#8]
## Value proposition

**As a user
I want to see the time left until an event starts
So that I can plan my time better**

## Description

- The time left until the start of the event is displayed

## Acceptance criteria

- [x] All events on the `EventListPage` display the `timeLeft` 🖼️
- [x] An event on the `EventDetailPage` display the `timeLeft` 🖼️
- [x] If an event is in the past, it is not displayed on the `EventListPage` 🖼️
- [x] The `timeLeft` value is refreshed every minute

## Tasks

- [x] Set a useEffect() on the `EventListPage` with an interval of 1 min
- [x] Acceptance criteria with 🖼️ requires component testing

Complexity: XL

**Comment by PacoSchwab** [comment]
LGTM, nice!
